### PR TITLE
Scalafmt: limit width

### PR DESCRIPTION
**Pull request by ennru**
Let's try a max column of 60.

Config in the first commit.
Applied to all sbt projects in the second commit.

References #207

### CODE REVIEW

**Review by ignasi35 — COMMENTED** [review]
60 seems a bit too aggressive.

**Comment by ennru** [comment]
Works nicely on my phone.

**Comment by ignasi35** [comment]
Hmm, not only 60 seems a bit too aggressive (I'm testing at maximum width):

Screenshot 2020-10-13 at 14 16 41


... but we'll also have to manually review comments:

Screenshot 2020-10-13 at 14 17 38

The comment on the screenshot spans until 96 chars and is not split. To be done on a separate PR.

Also on a separate PR: manually maintained snippets. E.g. `grpcurl` commands.

**Review by ignasi35 — APPROVED** [review]

**Comment by ennru** [comment]
The bullet markers `<1>` often are misplaced now.

**Pull request merged**
