### PR TITLE
Use  IAM instead of ACM for importing certificate

### PR DESCRIPTION
**Pull request by ygree**
Resolves: #https://github.com/lightbend/akka-platform-meta/issues/167

### CODE REVIEW

**Review by andreaTP — APPROVED** [review]

**Comment by andreaTP** [comment]
looks good! @ygree did you tested it?

**Comment by ygree** [comment]
> looks good! @ygree did you tested it?

Yes. I could add, get and delete the cert. I didn't test the ingress though. Do you think it's worth doing so?

**Comment by andreaTP** [comment]
> Do you think it's worth doing so?

yes, please 🙏  we have had so many hiccups there I would rather stay on the safe side and have another person go through the guide.

**Comment by ygree** [comment]
> > Do you think it's worth doing so?
> 
> yes, please 🙏 we have had so many hiccups there I would rather stay on the safe side and have another person go through the guide.

I just finished testing and it all works as expected with `aws iam upload-server-certificate`.

**Pull request merged**
