### PR TITLE
use new releases for jdbc plugin and projections

### PR DESCRIPTION
**Pull request by octonato**
First commit updates the seeds, second commit is just the copy-files. 

So, better to review only bb9a1cfd12ca06daa798f9cf2cfba04b0700dd0c

### CODE REVIEW

**Comment by patriknw** [comment]
I would expect some more in the how-to examples

**Comment by octonato** [comment]
> I would expect some more in the how-to examples

What you mean by some more? We have been using the the snapshots for a while already and using the new schema in the examples. We are only moving now to the stable release.

**Comment by patriknw** [comment]
More dependencies. For example docs-source/docs/modules/how-to/examples/shopping-cart-service-cassandra-java/pom.xml

**Comment by octonato** [comment]
> More dependencies. For example docs-source/docs/modules/how-to/examples/shopping-cart-service-cassandra-java/pom.xml

yep, I missed those. Will fix it.

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
