### PR TITLE
Remove unnecessary info regarding last publish

### PR DESCRIPTION
**Pull request by ignasi35**
References #181

@rstento is this info something we want to keep around?

### CODE REVIEW

**Comment by ignasi35** [comment]
> @rstento is this info something we want to keep around?

I mean, maybe adding the information regarding last publish is:

1. unnecessary
2. may be handled on the theme (see #268) so it's part of all pages (?)

**Comment by rstento** [comment]
> > @rstento is this info something we want to keep around?
> 
> I mean, maybe adding the information regarding last publish is:
> 
> 1. unnecessary
> 2. may be handled on the theme (see #268) so it's part of all pages (?)

If it ends up being part of the theme it's good to remove. It is very handy to be able to verify that publication occurred at the time we expected it to.

**Comment by rstento** [comment]
@ignasi35, I don't see it as part of the theme.  Few people are going to notice this, it is at the bottom of the page and only on one page, however, it is very useful for us as authors to be able to take a quick look and verify when the last changes were made and whether changes we just made have been published yet. I use this a lot.

**Comment by ignasi35** [comment]
> @ignasi35, I don't see it as part of the theme. Few people are going to notice this, it is at the bottom of the page and only on one page, however, it is very useful for us as authors to be able to take a quick look and verify when the last changes were made and whether changes we just made have been published yet. I use this a lot.

My thinking was that we can add this information hidden in the HTML. By doing that on the theme it'd be available on any page. Then, as authors we can verify that info on every page (not even need to go find the info in a particular page). 

I understand your use-case and I'm fine closing this PR. May eventually come with an alternative but this is not something we should worry about now.

Thanks @rstento :-)

**Pull request closed without merging**
