### PR TITLE
move local config section to template.adoc

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Review by octonato — APPROVED** [review]

**Comment by patriknw** [comment]
@ennru Do you know what is wrong with the link checker? Failing in PR validation.

**Comment by ennru** [comment]
Looks like Lagom docs were unreachable at the time

https://travis-ci.com/github/akka/akka-platform-guide/jobs/402429730#L328

https://travis-ci.com/github/akka/akka-platform-guide/jobs/402429730#L451

**Comment by patriknw** [comment]
but that seems to be very frequent. I checked those links in browser right afterwards and they worked fine

**Comment by patriknw** [comment]
I mean, it wasn't only this job. It has been several PRs and also master

**Comment by ennru** [comment]
Ok, if it's a pain we shouldn't run it on Travis.

**Pull request merged**
