### PR TITLE
Adds reactive disambiguation

### PR DESCRIPTION
**Pull request by ignasi35**
References #247 and #211

### CODE REVIEW

**Review by octonato — COMMENTED** [review]
I don't know if we should add this. Why do we need a disambiguation page at that stage? Where in the guide are we creating ambiguity that we need to solve? 

I feel that this is adding information on top of information, making the guide looks overwhelming. 

I don't think that making a distinction between Reactive Manifesto, Reactive Principles, Reactive System and Reactive Stream will help users understand how to build applications using Akka. I would prefer to have the guide more down to earth and directly covering clear use cases for Akka. 

If we believe its ambiguous, we should add such a page on the Reactive Foundation website, not here.

**Comment by ignasi35** [comment]
Multiple concepts refer to the Reactive Principles. Several concepts are justified as "The preferred choice to stay reactive" and link to some term in the glossary of the reactive manifesto. Akka Streams reference the Reactive Streams.

Disambiguating Reactive Programming and Reactive systems is such an important topic that it even produced a whitepaper. The latest addition to the mix, the Reactive Principles and the Reactive Patterns, only made the mix worse. 

Having a page we can link to anytime we need to disambiguate will put a nail on the discussion.

**Review by patriknw — APPROVED** [review]
LGTM, but I agree with Renato's concern that the number of concepts are becoming scary and overwhelming. That can be solved by Ignasi's suggestion of not presenting all of them in the navigation list.

I think those are fundamental enough to add but let's select additional concepts carefully (Ignasi and I have talked about this).

**Comment by ignasi35** [comment]
> LGTM, but I agree with Renato's concern that the number of concepts are becoming scary and overwhelming. That can be solved by Ignasi's suggestion of not presenting all of them in the navigation list.
> 
> I think those are fundamental enough to add but let's select additional concepts carefully (Ignasi and I have talked about this).

I have no intent on adding more concepts and I've already trimmed the list from the original plan drafted in #59.

**Pull request merged**
