### PR TITLE
Fix Travis YAML

### PR DESCRIPTION
**Pull request by ennru**
It keeps giving joy!

### CODE REVIEW

**Review by jrudolph — APPROVED** [review]
LGTM, fun!

**Review by patriknw — APPROVED** [review]
Ouch, I have exceeded the number of yaml mistakes for this century

**Comment by patriknw** [comment]
IntelliJ copy paste in yaml is completely broken. On the other hand it has syntax validation, that I seems to ignore.

**Comment by ennru** [comment]
>  I have exceeded the number of yaml mistakes for this century

There is no upper limit, I'm afraid.

**Pull request merged**
