### PR TITLE
build: try to use official adoptopenjdk package for debian instead of jabba

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM

**Review by ennru — CHANGES_REQUESTED** [review]
Please don't opt for a special solution in this repo.
We need to understand what happens and switch to a proper solution.

**Comment by ennru** [comment]
As the cache cleaning hack was successful, I'll close this.

**Comment by jrudolph** [comment]
Using the official package is far less special than using jabba or any other third party installer. :) After all it's probably jabba which got the cache into the broken state...

**Pull request closed without merging**
