### PR TITLE
correct proto index

### PR DESCRIPTION
**Pull request by patriknw**
reported by @mckeeh3

### CODE REVIEW

**Comment by ignasi35** [comment]
Should [the final file](
https://github.com/akka/akka-platform-guide/blob/main/docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-scala/src/main/protobuf/ShoppingCartService.proto#L44-L47) switch the field order, then?

**Comment by patriknw** [comment]
> Should the final file switch the field order, then?

I don't know if it's only me but I tend to put repeated fields at the end.

I don't think it matters that they differ.

**Comment by ignasi35** [comment]
But with this PR we'd be changing the tag of the `Items` field.
```
// from the final codebase
message Cart {
    bool checkedOut = 1;
    repeated Item items = 2;
}
```
```
// from steps 01 and 02
message Cart {
    repeated Item items = 1;
}
```

**Comment by ignasi35** [comment]
My "protobuf evolutions fu" is veeeery rusted.

**Comment by ignasi35** [comment]
I mean, it's a small thing but users following the tutorial may have `Cart` snapshots the final codebase would not be able to read(?). 
Also, implementing this with evolution of protos in mind will simplify the `How to evolve proto schemas` page (in #28).

**Review by ignasi35 — APPROVED** [review]

**Pull request merged**
