### PR TITLE
Fix path to deployment images

### PR DESCRIPTION
**Pull request by seglo**
As reported by Hugh

### CODE REVIEW

**Comment by seglo** [comment]
@ennru Should link validator check image paths?

**Review by patriknw — APPROVED** [review]
LGTM, should probably also be pushed to `current` asap since published docs are broken.
cc @thothmoses

**Comment by ennru** [comment]
> Should link validator check image paths?

That would be a feature request. I'll send you my rates.

**Comment by thothmoses** [comment]
Please merge this into Current.

**Comment by ignasi35** [comment]
> @ignasi35 Please merge this into Current.

See #698 :D

**Pull request merged**
