### PR TITLE
Update to Akka HTTP 10.2.8

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Comment by jrudolph** [comment]
(accidentally pushed directly to master before, but reverted those commits)

**Comment by patriknw** [comment]
We would also need an update in the bom for maven: https://github.com/lightbend/akka-platform-dependencies

**Comment by jrudolph** [comment]
> We would also need an update in the bom for maven: [lightbend/akka-platform-dependencies](https://github.com/lightbend/akka-platform-dependencies)

That's done now isn't it? Or do we have to create a new release for that and update the poms here?

**Comment by patriknw** [comment]
Yes, release and update here needed

**Comment by patriknw** [comment]
I have tagged `0.2.4` in bom project so you can update maven dependencies here when that has been published.

**Comment by jrudolph** [comment]
> I have tagged `0.2.4` in bom project so you can update maven dependencies here when that has been published.

Done!

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
