### PR TITLE
Use Akka and Akka HTTP BOM pom.xml

### PR DESCRIPTION
**Pull request by ennru**
This is WIP until Akka and Akka HTTP release their next versions.

### CODE REVIEW

**Review by patriknw — COMMENTED** [review]
nice!

**Review by ignasi35 — APPROVED** [review]
I think this can be simplified further thanks to the power the BOM brings, actually.

For example, the explicit dependency to `akka-http-jackson_{scala.bin}` was necessary to fix an incompatibility with a transitive dependency brought in by akka-management. Maybe `akka-discovery_` can be gone too.
I suspect we may also be able to remove `akka-http2-support_{scala.bin}` (and other on the `akka-http` set) since I suspect that explicit dependency is only necessary to fix the issue when bringing in akka-grpc.

**Review by ignasi35 — CHANGES_REQUESTED** [review]
(pressed the wrong button, sorry)

Apparently, when the PR is DRAFT I can't dismiss my own Approval, or maybe that's normal limitation?

**Comment by ennru** [comment]
@ignasi35 You are right, all explicit dependencies to Akka HTTP can go as Akka gRPC brings them in and the BOM makes sure we get the correct version.

**Review by ignasi35 — APPROVED** [review]

**Comment by ennru** [comment]
See #466 instead

**Pull request closed without merging**
