### PR TITLE
structure of concepts, #179

### PR DESCRIPTION
**Pull request by patriknw**
Taking some ideas from https://github.com/akka/akka-platform-guide/pull/184 and suggesting this structure (unfolded):

Screenshot 2020-10-21 at 12 11 13

References #179

### CODE REVIEW

**Comment by patriknw** [comment]
wdyt @rstento @ignasi35 ?

**Comment by ignasi35** [comment]
Looks great. It's very in sync with the contents required for the tutorial and the order in which they appear on the tutorial.

**Review by ignasi35 — APPROVED** [review]

**Comment by octonato** [comment]
can we make the last section's title what shorter? 

"Patterns and techniques for Reactive Microservices" is a mouthful. 

I know this was already discussed, but I don't think we came to a conclusion.

Some suggestions: 

* Reactive Microservices Architecture
* Reactive Microservices Concepts
* Reactive Microservices Patterns

I like architecture. What we are listing is a bunch of patterns and techniques that when applied define how your architecture looks like. You can pick a few from the list and if you follow the reactive principles (and Akka helps you on that), you end up with a Reactive Microservices Architecture. 

Maybe the only one that is not fitting here is the deployment. Debatable. 

WDYT?

**Comment by patriknw** [comment]
> can we make the last section's title what shorter?

@ignasi35 had some opinions about that, not sure what it was

Architecture might sound "bigger than it is", and it also has many different meanings for different people

Reactive Microservices Patterns could work, but I think Ignasi thought some of these are not patterns. For example the last about Docker/Kubernetes doesn't fully fit in here. Maybe we should leave that one out (from nav) now, and introduce when we know more about how we will do deployments?

**Comment by octonato** [comment]
> Reactive Microservices Patterns could work, but I think Ignasi thought some of these are not patterns. For example the last about Docker/Kubernetes doesn't fully fit in here. Maybe we should leave that one out (from nav) now, and introduce when we know more about how we will do deployments?

if that's the reason for not choosing "Patterns", then yes let's leave it out. It probably deserve its own section. 

Could "Reactive Microservices Concepts" be a better choice? Pattern is also overloaded. Concepts is generic enough.

**Comment by ignasi35** [comment]
We discussed a few other formulas in https://github.com/akka/akka-platform-guide/pull/184#discussion_r486421919 and https://github.com/akka/akka-platform-guide/pull/184#discussion_r486832089. Here are a few of those formulas:

* `How to design Reactive` <-- can be confused with the `How to...` section of the guide
* `Designing Reactive`
* `Useful for Reactive`

Or a new one I think we didn't consider yet:

* `Designing Reactive Microservices` 

So the NAV would look like:

* Akka modules for Microservices
* What is Reactive?
* Designing Reactive Microservices

**Comment by octonato** [comment]
Designing Reactive Microservices is also good to me

**Comment by patriknw** [comment]
+1 to Designing Reactive Microservices

**Comment by rstento** [comment]
+1 to Designing Reactive Microservices

**Review by rstento — APPROVED** [review]
LGTM when "Designing Reactive Microservices" replaces the longer title.

**Review by octonato — APPROVED** [review]

**Pull request merged**
