### PR TITLE
Bump Akka to 2.6.13 and Scala to 2.13.5

### PR DESCRIPTION
**Pull request by johanandren**

### CODE REVIEW

**Comment by patriknw** [comment]
There should be a few more in the how-to projects.

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Potentially failing every time with https://github.com/akka/akka-platform-guide/issues/591

**Comment by ignasi35** [comment]
I'll merge and we can PR the Akka HTTP version bump separately.

**Pull request merged**
